apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: DIMO
spec:
  owner: team-draco
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: mobile-ordering-api
spec:
  type: backend
  lifecycle: production
  owner: team-draco
  system: dimo
  providesApis: [mobile-ordering-api]
---
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-api
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: mobile-ordering-api
spec:
  type: java
  lifecycle: production
  owner: team-draco
  system: dimo
  
